### ISSUE TITLE
Don’t use lowercase class names.

### ISSUE THREAD

**Issue by OmenDoesStuff** [ziuee/cPractice#2]
It’s just bad practice in general, so don’t.

**Comment by ziuee** [comment]
Never used lowercase class names?

**Comment by OmenDoesStuff** [comment]
> Never used lowercase class names?

I’ve never used them, but I know it’s bad practice to.

**Comment by ziuee** [comment]
But why tell me when I never done so?

**Comment by OmenDoesStuff** [comment]
> But why tell me when I never done so?

You did. cPractice.java & cPracticeAPI.java

**Comment by ziuee** [comment]
That's the name of the core, I'm not supposed to use uppercase names there.

**Comment by OmenDoesStuff** [comment]
> That's the name of the core, I'm not supposed to use uppercase names there.

Yeah, but still it’s bad practice so don’t use them
